version: '3'

services:
  backend:
    build:
      # image: hyeeok/spap:backend
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    mem_limit: 1g

  postgres:
    # image: hyeeok/spap:postgres-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spap
    mem_limit: 1g
