"""Remove session table

Revision ID: 06c4b0a89584
Revises: 4a0d2ae5f270
Create Date: 2024-01-15 13:16:03.452671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c4b0a89584'
down_revision: Union[str, None] = '4a0d2ae5f270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
