"""Add Auth models

Revision ID: b68a617e58ed
Revises: 525a0b6d07ca
Create Date: 2024-01-10 17:10:19.955805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68a617e58ed'
down_revision: Union[str, None] = '525a0b6d07ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('users_profile_info',
    sa.Column('user_profile_info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_profile_info_id')
    )
    op.create_index(op.f('ix_users_profile_info_user_profile_info_id'), 'users_profile_info', ['user_profile_info_id'], unique=False)
    op.create_table('users_security_info',
    sa.Column('user_security_info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_security_info_id')
    )
    op.create_index(op.f('ix_users_security_info_user_security_info_id'), 'users_security_info', ['user_security_info_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_security_info_user_security_info_id'), table_name='users_security_info')
    op.drop_table('users_security_info')
    op.drop_index(op.f('ix_users_profile_info_user_profile_info_id'), table_name='users_profile_info')
    op.drop_table('users_profile_info')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
