"""create table

Revision ID: d28cd7d24d75
Revises: 
Create Date: 2024-01-30 13:39:10.505020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28cd7d24d75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('current_team', sa.String(), nullable=True),
    sa.Column('market_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_index(op.f('ix_players_rank'), 'players', ['rank'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('users_profile_info',
    sa.Column('user_profile_info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_profile_info_id')
    )
    op.create_index(op.f('ix_users_profile_info_user_profile_info_id'), 'users_profile_info', ['user_profile_info_id'], unique=False)
    op.create_table('users_security_info',
    sa.Column('user_security_info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_security_info_id')
    )
    op.create_index(op.f('ix_users_security_info_user_security_info_id'), 'users_security_info', ['user_security_info_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_security_info_user_security_info_id'), table_name='users_security_info')
    op.drop_table('users_security_info')
    op.drop_index(op.f('ix_users_profile_info_user_profile_info_id'), table_name='users_profile_info')
    op.drop_table('users_profile_info')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_rank'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
